all: forth3.exe

# forth0.exe is a forth compiler written in C.
forth0.exe: forth0.c
	gcc forth0.c -W -Wall -Werror -O3 -o forth0.exe

# forth1.exe is a forth compiler written in forth,
# but generated by a program written in C.
forth1.exe: forth0.exe core.ft msvcrt.ft forth.ft
	cat core.ft msvcrt.ft forth.ft | ./forth0.exe forth1.exe

# forth2.exe is a forth compiler written in forth,
# and generated by a program written in forth.
forth2.exe: forth1.exe core.ft msvcrt.ft forth.ft
	echo core.ft msvcrt.ft forth.ft --save forth2.exe | ./forth1.exe

# forth3.exe is a forth compiler written in forth,
# and generated by a program written in forth.
forth3.exe: forth2.exe core.ft msvcrt.ft forth.ft
	echo core.ft msvcrt.ft forth.ft --save forth3.exe | ./forth2.exe

.PHONY: test
test:
	tests/test.sh

.PHONY: clean
clean:
	rm -f *.exe *.exe.stackdump *~ tests/*.exe tests/*~ tests/*.exe.stackdump
